import type { LatestNowcastResponse } from "./nowcast";
import type { AuditEvent, WarningDraft } from "./warnings";

const now = () => new Date().toISOString();
const cube = (values: number[]) => ({ lead_minutes: [10,20,30,40,50,60], values: values.map((value) => [[value,value],[value,value]]) });
const storm = (track_id: string, latitude: number, longitude: number, tier: string, probability: number, confidence: number, impact_index: number, affected_areas: string[], speed: number) => ({ track_id, latitude, longitude, tier, probability, confidence, impact_index, affected_areas, velocity: { speed_km_h: speed, direction_degrees: 45 }, trend: "intensifying", source_attribution: { "Radar / Precipitation": .32, Satellite: .24, Lightning: .2, "Ground Stations": .1, NWP: .14 }, exposed_infrastructure: [{ type: "hospital" }, { type: "power" }] });
export const mockNowcast = (): LatestNowcastResponse => ({ cycle_id: "DEMO-IND-001", generated_at: now(), domain: { latitude: [6, 38], longitude: [68, 98], resolution_degrees: .25 }, data_status: { overall: "demo", sources: ["INSAT-3D", "Lightning Network", "Ground Stations", "NWP"].map((source) => ({ source, provider: "demo", mode: "sample", is_synthetic: true, state: "synthetic" as const, observed_at: now(), reason: "Local demonstration dataset" })) }, predictions: { storm_probability: cube([.87,.83,.78,.72,.66,.59]), lightning_probability: cube([.72,.76,.69,.61,.53,.45]), storm_confidence: cube([.91,.89,.87,.84,.8,.76]), lightning_confidence: cube([.88,.86,.84,.8,.76,.72]) }, storms: [storm("AST-024", 20.0, 74.0, "HIGH", .87, .91, .82, ["Nashik", "Dhule", "Jalgaon"], 42), storm("AST-019", 29.1, 76.0, "SEVERE", .91, .88, .91, ["Hisar", "Rohtak", "Jhajjar"], 51), storm("AST-031", 26.1, 91.7, "HIGH", .76, .86, .76, ["Guwahati", "Nagaon"], 37), storm("AST-028", 13.1, 77.6, "HIGH", .73, .89, .73, ["Bengaluru Rural", "Kolar"], 32), storm("AST-042", 22.5, 88.4, "MODERATE", .64, .84, .59, ["Kolkata", "Howrah"], 28), storm("AST-047", 13.1, 80.3, "MODERATE", .57, .81, .48, ["Chennai", "Tiruvallur"], 24)] });
export let mockDrafts: WarningDraft[] = ["AST-024", "AST-019", "AST-031", "AST-028"].map((id, index) => ({ warning_id: `WARN-${id}`, status: "pending", payload: { storm_id: id, tier: index === 1 ? "SEVERE" : "HIGH", affected_areas: mockNowcast().storms[index].affected_areas.join(" · "), impact_index: [82,91,76,73][index], eta: [18,12,24,21][index], message: "Review this AI-assisted draft before transmission." }, created_at: now(), decided_at: null, decided_by: null, transmitted: false }));
export let mockAudit: AuditEvent[] = [];
