const STORMS=[
 {id:'AST-024',name:'Delhi–NCR convergence',lat:28.61,lng:77.21,tier:'SEVERE',prob:87,confidence:91,lightning:74,speed:42,direction:48,eta:18,impact:82,trend:'GROWING',areas:'Delhi · Gurugram · Ghaziabad',exposure:8,color:'#ff4d5e',attr:{Radar:31,Satellite:24,Lightning:19,'Ground stations':11,NWP:15},infra:[['District Hospital',28.66,77.18],['IGI Airport',28.56,77.10]]},
 {id:'AST-019',name:'Kolkata outer corridor',lat:22.57,lng:88.36,tier:'HIGH',prob:81,confidence:88,lightning:69,speed:38,direction:132,eta:25,impact:77,trend:'GROWING',areas:'North 24 Parganas · Howrah',exposure:6,color:'#ffb547',attr:{Radar:28,Satellite:29,Lightning:21,'Ground stations':8,NWP:14},infra:[['SSKM Hospital',22.54,88.34],['Howrah Junction',22.59,88.34]]},
 {id:'AST-011',name:'Konkan coastal cell',lat:19.08,lng:72.88,tier:'HIGH',prob:79,confidence:84,lightning:58,speed:35,direction:60,eta:31,impact:74,trend:'STEADY',areas:'Mumbai Suburban · Thane',exposure:5,color:'#e94f9f',attr:{Radar:35,Satellite:22,Lightning:17,'Ground stations':10,NWP:16},infra:[['KEM Hospital',19,72.84],['Mumbai Airport',19.09,72.87]]},
 {id:'AST-031',name:'Brahmaputra valley cell',lat:26.14,lng:91.74,tier:'MODERATE',prob:67,confidence:81,lightning:62,speed:29,direction:36,eta:42,impact:61,trend:'DECAYING',areas:'Kamrup Metropolitan',exposure:3,color:'#28d7e8',attr:{Radar:24,Satellite:30,Lightning:23,'Ground stations':9,NWP:14},infra:[['Guwahati Medical College',26.11,91.79]]}
];
const SOURCES=[['Radar / GPM','LIVE','live'],['Satellite / INSAT','LIVE','live'],['Lightning proxy','SYNTHETIC','synthetic'],['Ground stations','PENDING','pending'],['NWP fields','LIVE','live']];
let map,stormLayers=[],traj=[],infra=[],selected=null,lead=0,playing=false,timer,infraOn=false,degraded=false,warningChoice=0;
const $=id=>document.getElementById(id),d=Math.PI/180;
function init(){map=L.map('map',{zoomControl:false,attributionControl:false}).setView([22.59,78.96],5);L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{maxZoom:19}).addTo(map);renderHealth();renderMap();bind();loadApi()}
async function loadApi(){try{let r=await fetch('/api/v1/nowcast/latest');if(!r.ok)throw 0;let a=await r.json();$('api-status').textContent=a.data_status.overall.toUpperCase();$('api-status').style.color=a.data_status.overall==='complete'?'#4de1b1':'#ffb547'}catch{$('api-status').textContent='DEMO CYCLE'}}
function point(s,t=lead){const k=s.speed*t/60;return{lat:s.lat+k*Math.cos(s.direction*d)/111,lng:s.lng+k*Math.sin(s.direction*d)/(111*Math.cos(s.lat*d))}}
function clear(){[stormLayers,traj,infra].forEach(a=>a.forEach(x=>map.removeLayer(x)));stormLayers=[];traj=[];infra=[]}
function renderMap(){clear();STORMS.forEach(s=>{let p=point(s);stormLayers.push(L.circle([p.lat,p.lng],{radius:43000+lead*320,stroke:false,fillColor:s.color,fillOpacity:.16,className:'storm-field'}).addTo(map));let m=L.marker([p.lat,p.lng],{icon:L.divIcon({className:'storm-icon',html:`<div class="storm-marker ${selected===s?'selected':''}" style="--color:${s.color}"><em>${s.id}</em></div>`,iconSize:[64,64],iconAnchor:[32,32]})}).addTo(map);m.on('click',()=>select(s));stormLayers.push(m);if(selected===s){trajectory(s);if(infraOn)facility(s)}})}
function trajectory(s){let pts=[];for(let t=0;t<=60;t+=10){let p=point(s,t);pts.push([p.lat,p.lng])}traj.push(L.polyline(pts,{color:'#7c5cff',weight:3,opacity:.95,dashArray:'8 9'}).addTo(map));let p=point(s,60);traj.push(L.polygon([[p.lat,p.lng],[p.lat+.75,p.lng+.35],[p.lat+.15,p.lng+1.1]],{color:'#28d7e8',weight:1,fillColor:'#7c5cff',fillOpacity:.14}).addTo(map))}
function facility(s){s.infra.forEach(([name,lat,lng])=>{infra.push(L.circleMarker([lat,lng],{radius:5,color:'#ffc857',fillColor:'#ffc857',fillOpacity:1}).bindTooltip(`${name}<br>ETA ${s.eta} MIN`).addTo(map));traj.push(L.polyline([[point(s).lat,point(s).lng],[lat,lng]],{color:'#ffc857',weight:1,opacity:.45,dashArray:'3 6'}).addTo(map))})}
function select(s){selected=s;$('intelligence-panel').classList.add('visible');$('storm-id').textContent=s.id;$('storm-tier').textContent=`${s.tier} RISK · ${s.trend}`;$('storm-probability').textContent=`${Math.max(48,s.prob-lead*.17)}%`;$('storm-confidence').textContent=`${degraded?s.confidence-7:s.confidence}%`;$('storm-lightning').textContent=`${s.lightning}%`;$('storm-speed').textContent=`${s.speed} KM/H`;$('storm-eta').textContent=`${Math.max(4,s.eta-(lead*.15|0))} MIN`;$('storm-vector').textContent=`${s.speed} KM/H  NE →`;$('storm-place').textContent=`Projected through ${s.areas} at T+${lead}.`;$('review-selected').disabled=false;$('impact-score').textContent=s.impact;$('impact-tier').textContent=`${s.tier} PRIORITY`;$('confidence-contribution').textContent=`${Math.round(s.confidence*.35)}%`;$('exposure-contribution').textContent=`${Math.round(s.exposure*5)}%`;$('trend-contribution').textContent=s.trend==='GROWING'?'27%':'18%';$('attribution-bars').innerHTML=Object.entries(s.attr).map(([k,v])=>`<div class="bar-row"><span>${k}</span><div class="bar"><i style="width:${v}%"></i></div><b>${v}%</b></div>`).join('');map.flyTo([s.lat,s.lng],6,{duration:.65});renderMap()}
function setLead(v){lead=+v;$('lead-slider').value=lead;$('lead-label').textContent=lead?`T+${lead} MIN`:'NOW';document.querySelectorAll('.ticks button').forEach(b=>b.classList.toggle('active',+b.dataset.lead===lead));selected?select(selected):renderMap()}
function renderHealth(){$('source-health').innerHTML=SOURCES.map(([n,state,c])=>{if(n.startsWith('Ground')&&degraded){state='DELAYED';c='delayed'}let col=c==='live'?'#4de1b1':c==='delayed'?'#ffb547':c==='synthetic'?'#ffc857':'#e94f9f';return `<div class="source-row"><span><i class="live-dot" style="background:${col};box-shadow:none;margin-right:6px"></i>${n}</span><b class="source-state state-${c}">${state}</b></div>`}).join('');$('health-note').textContent=degraded?'Prediction confidence reduced by 7%: ground-station feed delayed.':'Synthetic and pending inputs are explicitly labelled, never presented as observed.'}
function openWarnings(){$('warning-center').classList.add('open');warningChoice=selected?Math.max(0,STORMS.indexOf(selected)):0;renderWarnings()}
function closeWarnings(){$('warning-center').classList.remove('open')}
function renderWarnings(){let list=STORMS.slice(0,3);$('warning-list').innerHTML=list.map((s,i)=>`<button class="warning-item ${i===warningChoice?'active':''}" data-warning="${i}"><b>${s.id} · ${s.tier}</b><span>${s.areas}</span><small>ETA ${s.eta} MIN · IMPACT ${s.impact}</small></button>`).join('');document.querySelectorAll('[data-warning]').forEach(x=>x.onclick=()=>{warningChoice=+x.dataset.warning;renderWarnings()});let s=list[warningChoice];$('warning-review-content').innerHTML=`<div class="eyebrow">WARNING DRAFT / ${s.id}</div><h1 class="review-title">${s.tier} thunderstorm<br>risk advisory.</h1><p class="review-sub">${s.areas} · ASTRA recommends forecaster review before issuance.</p><div class="review-facts"><div><span>ETA</span><b>${s.eta} MIN</b></div><div><span>CONFIDENCE</span><b>${s.confidence}%</b></div><div><span>IMPACT</span><b>${s.impact}</b></div><div><span>EXPOSURE</span><b>${s.exposure} SITES</b></div></div><label class="eyebrow">FORECASTER MESSAGE</label><textarea>Thunderstorm activity is likely over ${s.areas} within the next ${s.eta} minutes. Avoid open areas and follow local authority guidance.</textarea><p class="human">HUMAN REVIEW REQUIRED · ASTRA NEVER AUTOMATICALLY DISPATCHES WARNINGS.</p><div class="review-actions"><button id="edit-warning">EDIT</button><button class="approve" id="approve-warning">APPROVE WARNING</button><button class="dismiss" id="dismiss-warning">DISMISS</button></div>`;$('edit-warning').onclick=()=>toast('Draft is editable. Changes remain pending forecaster approval.');$('approve-warning').onclick=approve;$('dismiss-warning').onclick=()=>{toast('Warning dismissed. Decision recorded in this prototype.');closeWarnings()}}
function approve(){let s=STORMS[warningChoice];closeWarnings();$('confirmation-detail').textContent=`Senior Forecaster · 08:42 IST · Audit ID ASTRA-W-${String(s.impact).padStart(5,'0')}`;$('confirmation').classList.add('show');setTimeout(()=>{$('confirmation').classList.remove('show');toast('Approved draft retained for audit review — not dispatched.')},2600)}
function toast(m){let e=$('toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3000)}
function bind(){$('lead-slider').oninput=e=>setLead(e.target.value);document.querySelectorAll('[data-lead]').forEach(b=>b.onclick=()=>setLead(b.dataset.lead));$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'❚❚':'▶';if(playing)timer=setInterval(()=>setLead(lead>=60?0:lead+10),1000);else clearInterval(timer)};$('close-panel').onclick=()=>{$('intelligence-panel').classList.remove('visible');selected=null;renderMap()};$('impact-toggle').onclick=()=>$('impact-hud').classList.toggle('expanded');$('data-button').onclick=()=>$('data-popover').classList.toggle('visible');$('degrade-toggle').onclick=()=>{degraded=!degraded;renderHealth();if(selected)select(selected);toast(degraded?'Ground-station delay shown. Confidence reduced.':'Ground-station feed restored for this demonstration.')};document.querySelectorAll('.layer').forEach(b=>b.onclick=()=>{b.classList.toggle('active');if(b.dataset.layer==='infra'){infraOn=b.classList.contains('active');renderMap()}if(b.dataset.layer==='risk')$('map').style.filter=b.classList.contains('active')?'saturate(.9) brightness(.72) hue-rotate(20deg)':'saturate(.55) brightness(.58) contrast(1.15)';if(b.dataset.layer==='lightning')document.querySelector('.atmosphere').style.opacity=b.classList.contains('active')?'1':'.35'});$('warning-nudge').onclick=openWarnings;$('review-selected').onclick=openWarnings;$('warning-close').onclick=closeWarnings;document.querySelectorAll('.rail-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.rail-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.mode==='Warnings')openWarnings();if(b.dataset.mode==='Data')$('data-popover').classList.add('visible');if(b.dataset.mode==='Infrastructure'){document.querySelector('[data-layer="infra"]').classList.add('active');infraOn=true;renderMap()}toast(`${b.dataset.mode.toUpperCase()} MODE`)})}
document.addEventListener('DOMContentLoaded',init);
